version: 0.2

environment_variables:
  plaintext:
    DB_ROOT_PASSWORD: password
    DB_HOST: localhost
    DB_USER: mysql
    DB_PASSWORD: password

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      # - echo "mysql-server mysql-server/root_password password ${DB_ROOT_PASSWORD}" |debconf-set-selections
      # - echo "mysql-server mysql-server/root_password_again password ${DB_ROOT_PASSWORD}" |debconf-set-selections
      - echo install started on `date`
      - apt-get update
      - apt-get -y install nodejs
      - apt-get -y install nodejs-dev node-gyp libssl1.0-dev
      - apt-get -y install npm
      # - apt-get -y install mysql-server-5.7
      # - service mysqld start
      # - mysql -p${DB_ROOT_PASSWORD} -e "create database for rails_portfolio;"
      # - mysql -p${DB_ROOT_PASSWORD} -e "GRANT ALL ON *.* TO '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';"
      - update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
      - gem install bundler -v 1.17.2
      - bundle install
      # - bin/rails db:migrate RAILS_ENV=test 
  build:
    commands:
      - echo Build started on `date`
      - bundle exec rails test
  post_build:
    commands:
      - echo Build completed on `date`