# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 652a9be4db802758aa765b8647b3d09d811f03dc6c78a5e75c10656b6d04151d09e761fb7050375a2ffb07618ffff6b4be5f7034473b028f0db0b1da5d815822

test:
  secret_key_base: 45413f03cfb6074877b2f2ef066d4866767ca8a134fdf0526214c7d49256de068c236599ff2a9e8ca4ee010b128de17f0d0eb5000c0c0b80092fba2609962275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
